spring:
  datasource:
    url: jdbc:h2:tcp://localhost:1521/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

comment:
  service:
    url: http://localhost:1234

post:
  service:
    url: http://localhost:1235


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

