spring:
  datasource:
    url: jdbc:h2:tcp://localhost:1521/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

external:
  api:
    placeHolder: https://jsonplaceholder.typicode.com/


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

---
spring.config.activate.on-profile: wiremock
external:
  api:
    placeHolder: http://localhost:${wiremock.server.port}