name: run gradle task

on:
  workflow_call:
    inputs:
      task-name:
        required: true
        type: string
        description: gradle task name to run


jobs:
  run-gradle-task-workflow:
    name: ${{ inputs.task-name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@750cdda3edd6d51b7fdfc069d2e2818cf3c44f4c # v3.3.1
      - name: Run test1
        run: ./gradlew ${{ inputs.task-name }}