name: multiple job concurrency

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  job1:
    uses: ./.github/workflows/executeGradleTask.yml
    with:
      task-name: test1
    secrets: inherit

  job2:
    uses: ./.github/workflows/executeGradleTask.yml
    with:
      task-name: test2
    secrets: inherit

  job3:
    uses: ./.github/workflows/executeGradleTask.yml
    with:
      task-name: test3
    secrets: inherit