name: multiple job pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  job1:
    uses: ./.github/workflows/executeGradleTask.yml
    with:
      task-name: plusTest

  job2:
    uses: ./.github/workflows/executeGradleTask.yml
    with:
      task-name: minusTest

  job3:
    uses: ./.github/workflows/executeGradleTask.yml
    with:
      task-name: mathTest

  job4:
    uses: ./.github/workflows/executeGradleTask.yml
    with:
      task-name: plusOrMinusTest
    needs: [job1]