name: multiple job concurrency

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  job1:
    name: first gradle job
    uses: ./.github/workflows/executeGradleTask.yml
    with:
      task-name: test1
    secrets: inherit

  job2:
    name: second gradle job
    uses: ./.github/workflows/executeGradleTask.yml
    with:
      task-name: test1
    secrets: inherit

  job3:
    name: third gradle job
    uses: ./.github/workflows/executeGradleTask.yml
    with:
      task-name: test1
    secrets: inherit